[2023-09-25 18:23:57,822] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:23:57] "GET /:id?id=4 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:24:09,685] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:24:11,999] ERROR log_exception() L1449 Exception on /:id [GET] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py", line 132, in get_list
    token = bearer.split()[1]
            ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
[2023-09-25 18:24:12,008] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:24:12] "[35m[1mGET /:id?id=4 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:25:28,034] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:25:43,324] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:25:48,797] ERROR log_exception() L1449 Exception on /:id [GET] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py", line 137, in get_list
    if not user:
           ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
[2023-09-25 18:25:48,803] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:25:48] "[35m[1mGET /:id?id=4 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:26:45,766] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:26:48,103] WARNING get_list() L145  Erro ao buscar lista #'4', Lista não encontrada - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L145 
[2023-09-25 18:26:48,105] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:26:48] "[33mGET /:id?id=4 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:24,842] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:29,438] WARNING get_list() L146  Erro ao buscar lista #'4', Lista não encontrada - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L146 
[2023-09-25 18:27:29,440] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:29] "[33mGET /:id?id=4 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:33,069] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:33,480] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:33,481] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:33,481] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:33,657] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:27:33,952] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:33] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
