[2023-09-25 17:19:08,340] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:08] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:08,377] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:08] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:08,378] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:08] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:08,539] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:08] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:08,849] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:08] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:16,917] ERROR log_exception() L1449 Exception on /me [GET] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_my_lists() missing 1 required positional argument: 'headers'
[2023-09-25 17:19:16,923] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:16] "[35m[1mGET /me HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:27:18,762] ERROR log_exception() L1449 Exception on /me [GET] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_my_lists() missing 1 required positional argument: 'headers'
[2023-09-25 17:27:18,766] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:27:18] "[35m[1mGET /me HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:27:22,710] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:27:25,120] ERROR log_exception() L1449 Exception on /me [GET] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py", line 75, in get_my_lists
    token = bearer.split()[1]
            ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
[2023-09-25 17:27:25,126] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:27:25] "[35m[1mGET /me HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:28:30,672] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:37:26,188] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:37:28,781] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:37:28] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:37:29,071] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:37:29] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:37:29,118] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:37:29] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
