[2023-09-25 18:27:42,337] ERROR log_exception() L1449 Exception on /:id [GET] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py", line 137, in get_list
    token = bearer.split().get(1)
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
[2023-09-25 18:27:42,349] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:27:42] "[35m[1mGET /:id?id=4 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:31:45,921] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:32:08,259] WARNING get_list() L144  Erro ao buscar lista #'4', Lista não encontrada - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L144 
[2023-09-25 18:32:08,260] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:32:08] "[33mGET /:id?id=4 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:32:18,081] WARNING get_list() L144  Erro ao buscar lista #'3', Lista não encontrada - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L144 
[2023-09-25 18:32:18,082] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:32:18] "[33mGET /:id?id=3 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:32:23,061] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:32:23] "GET /:id?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:32:27,381] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:32:27] "GET /:id?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:32:32,203] WARNING get_list() L144  Erro ao buscar lista #'3', Lista não encontrada - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L144 
[2023-09-25 18:32:32,204] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:32:32] "[33mGET /:id?id=3 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:35:47,710] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:35:49,831] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:35:49] "GET /:id?id=3 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:35:57,329] WARNING get_list() L145  Erro ao buscar lista #'4', Lista não encontrada - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L145 
[2023-09-25 18:35:57,330] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:35:57] "[33mGET /:id?id=4 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:35:59,452] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:35:59] "GET /:id?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:36:03,281] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:36:03] "GET /:id?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 18:36:09,986] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 18:36:09] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 21:39:04,644] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.0.2:5000 (Press CTRL+C to quit) - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 21:39:08,198] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 21:39:08] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 21:39:08,251] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 21:39:08] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 21:39:08,253] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 21:39:08] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 21:39:08,253] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 21:39:08] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 21:39:08,450] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 21:39:08] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 21:39:08,465] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 21:39:08] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 22:04:42,273] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 22:04:42] "OPTIONS /me HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 22:04:42,348] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 22:04:42] "GET /me HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 22:05:37,372] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 22:05:37] "OPTIONS /me HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 22:05:37,391] INFO _log() L224  172.24.0.1 - - [25/Sep/2023 22:05:37] "GET /me HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-25 19:26:01,720] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.15.8:5002 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
